server:
  port: 8081
  ssl:
    enabled: false

bot:
  name: together_cook_bot
  token: 7114627884:AAG5vECaEOTwQfLbYOi9u6W1mWEeaU2d7lM
  uri: https://ac74-51-77-20-38.ngrok-free.app

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: constantin
    password: password
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message