server:
  port: 8084

spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username:
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: constantin
    password: password
    queues:
      registration-mail: registration_mail

service:
  activation:
    uri: http://127.0.0.1:8083/user/activation?id={id}