server:
  port: 8084

spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: techMailTg@yandex.ru
    password: fhyouulftvteqxpp

service:
  activation:
    uri: http://127.0.0.1:8083/user/activation?id={id}