server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: constantin
    password: password
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message
      registration-mail: registration_mail
  datasource:
    url: jdbc:postgresql://localhost:5431/cook_together_db
    username: constantin
    password: password
  jpa:
    generate-ddl: true

token: <add tg bot token>
service:
  file_info:
    uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
  file_storage:
    uri: https://api.telegram.org/file/bot{token}/{filePath}
  mail:
    uri: http://127.0.0.1:8084/mail/send

link:
  address: 127.0.0.1:8083
salt: 8De601a74a6c6H7b4E9c2f9f38cC5e66
