server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/cook_together_db
    username: constantin
    password: password
  jpa:
    generate-ddl: true
salt: 8De601a74a6c6H7b4E9c2f9f38cC5e66